id: I1E306A83
legacy_id: P009383
ocr_import_info:
  bdrc_scan_id: W1KG22125
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T07:58:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T12:56:12.521464+00:00'
last_modified: 2022-08-31 20:56:20.145130
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22125
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22125
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟློས་གར་རང་འབྱུང་ཁམས།
  author: ས་ཕུད་ཐུབ་བསྟན་དཔལ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.6885000964166453
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I1KG22195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22195
      total_pages: 138
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22195.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6885000964166453
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
