id: I1E306A83
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:59:45+00:00'
last_modified: '2022-06-08T10:37:28.773303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22125
  title: ཟློས་གར་རང་འབྱུང་ཁམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0709:
      image_group_id: I1KG22195
      title: ''
      total_pages: 138
      order: 1
      base_file: 0709.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
